# Generated by Django 3.2.9 on 2021-11-14 20:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время последнего изменения')),
                ('name', models.CharField(choices=[('WASTE_DISPOSAL_MACHINE', 'Машина для утилизации отходов'), ('ASPHALT_PAVER_MACHINE', 'Асфальтоукладчик'), ('BULLDOZER', 'Бульдозер')], default='BULLDOZER', max_length=22, verbose_name='Название техники/услуги')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время последнего изменения')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pick_up_address', models.CharField(max_length=255, verbose_name='Точка А')),
                ('drop_off_address', models.CharField(max_length=255, verbose_name='Точка Б')),
                ('status', models.CharField(choices=[('REQUESTED', 'Запрошен'), ('STARTED', 'Начата'), ('IN_PROGRESS', 'В процессе'), ('COMPLETED', 'Завершена')], db_index=True, default='REQUESTED', max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
