# Generated by Django 3.2.9 on 2021-11-15 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211115_0427'),
        ('trips', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Services',
        ),
        migrations.AlterField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trips_as_driver', to='users.driver', verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='rider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trips_as_rider', to='users.rider', verbose_name='Исполнитель'),
        ),
    ]
