# Generated by Django 3.2.9 on 2021-11-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_auto_20211115_0427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='drop_off_address',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='pick_up_address',
        ),
        migrations.AddField(
            model_name='trip',
            name='address',
            field=models.JSONField(default=list, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='trip',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='trip',
            name='payment_type',
            field=models.CharField(choices=[('CASH', 'Наличные'), ('CARD', 'Карта')], db_index=True, default='CASH', max_length=20, verbose_name='Тип оплаты'),
        ),
        migrations.AddField(
            model_name='trip',
            name='price',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Цена'),
        ),
    ]
