# Generated by Django 3.2.9 on 2021-11-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_auto_20211116_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Активный'), ('APPROVING', 'На подтверждении'), ('APPROVED', 'Подтвержден'), ('ON_WAY', 'В пути'), ('WAITING', 'В ожидании'), ('ON_TASK', 'На исполнении'), ('FINISHED', 'Завершен')], db_index=True, default='ACTIVE', max_length=20, verbose_name='Статус'),
        ),
    ]
