# Generated by Django 3.2.9 on 2021-11-15 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время последнего изменения')),
                ('name', models.CharField(choices=[('WASTE_DISPOSAL_MACHINE', 'Машина для утилизации отходов'), ('ASPHALT_PAVER_MACHINE', 'Асфальтоукладчик'), ('BULLDOZER', 'Бульдозер')], default='BULLDOZER', max_length=22, verbose_name='Название техники/услуги')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Список услуг',
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='driver',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='users.services', verbose_name='Техника'),
        ),
    ]
